### ISSUE TITLE
Misleading error message on missing environment value

### ISSUE THREAD

**Issue by mjswensen** [denodrivers/postgres#121]
With the following environment configuration:

```env
PGHOST=myhost
PGUSER=myuser
PGPASSWORD=mypassword
```

and the following contents in `main.ts`:

```ts
import { Client } from "https://deno.land/x/postgres/mod.ts";

const client = new Client();
```

deno-postgres throws this error when using `deno run --allow-env --allow-net main.ts`:

```
error: Uncaught ConnectionParamsError: Missing connection parameters: database. Connection parameters can be read from environment only if Deno is run with env permission (deno run --allow-env)
```

I'd propose the following solutions:

1. If `--allow-env` is passed, don't warn that "Connection parameters can be read from environment only if Deno is run with env permission"—it's confusing since `--allow-env` _was_ indeed passed. "Missing connection parameters: database." is sufficient.
2. If `PGDATABASE` is missing, default it to the value of `PGUSER`.

Thanks for work on this great package!

**Comment by ebebbington** [comment]
I'd say this notice is redundant (the env part), but maybe the first sentence could be improved upon to explain the context a bit more?

@hayd

**Comment by hayd** [comment]
That is confusing! 1. definitely would be a huge improvement.

Is 2. standard? What does node-postgres do here?
(IMO Using PGUSER as PGDATABASE feels a little too magical/not explicit, but if that's what other systems do then ok!)

**Comment by mjswensen** [comment]
Looks like from [this docs page](https://node-postgres.com/features/connecting) that both user name and database name are defaulted to `process.env.USER`, which I guess is a little different than defaulting one from the other.

**Comment by Soremwar** [comment]
Error message was improved on v0.5.0, just released

The error will now only show the second part of the warning when env permissions are not passed

Docs about values defaulting to env variables will be added soon
