### ISSUE TITLE
Todo: handle notice

### ISSUE THREAD

**Issue by andreespirela** [denodrivers/postgres#124]
Hello. I am getting an annoying console.log on my application coming from this module, so when postgres throws a notice for a query, I get "todo: handle notice" on my console.

**Comment by grantcarthew** [comment]
This is happening because of this: https://github.com/buildondata/deno-postgres/blob/6527ecc561f666054ca54a355ef1b2a51842eecb/connection.ts#L297

More importantly, the next while look doesn't handle `case "N"` for notices. I can't run DDL due to this. If you want, as a quick work around, clone `deno-postgres`, import from there, edit the case in the while look to break on "N".

**Comment by andreespirela** [comment]
@grantcarthew Sure, I would do that but my application is a framework so it’s not only me who uses it and I prefer it having this module as a dependency rather than downloading the whole folder and putting it my module. I hope you understand, regards.

**Comment by grantcarthew** [comment]
It's a workaround for now. Once this project gets attention then switch back. If you want to keep working on your framework whilst this is an issue, it will get you going.

**Comment by hayd** [comment]
Should it break? What's the correct behavior here?

**Comment by ebebbington** [comment]
Can't you just remove the `console.log` and replace it with a `// TODO(<name>) Handle notice`? Or am I missing something?

**Comment by biggledfred** [comment]
@ebebbington agreed it is a little confusing and the message doesn't provide context or anything useful.  If it is a TODO as a comment, if it should break due to incorrect config then it should do.  It took a little searching about to even know that it was coming from this module.

**Comment by mooxl** [comment]
Any updates on this?

**Comment by Soremwar** [comment]
@mooxl This was solved on v0.5.0.

Sorry for slow fixing, I'm the new mantainer and I'm doing everything I can to improve the library now!
