### ISSUE TITLE
Return objects rather than arrays

### ISSUE THREAD

**Issue by grantcarthew** [denodrivers/postgres#126]
The node.js project `node-postgres` or `pg` returns objects rather than rows of arrays. It was elegant to work with. Is there a reason this project only returns an array of arrays? Am I missing something?

**Comment by hayd** [comment]
IMO we should copy what node-postgres does.

**Comment by ebebbington** [comment]
What about something like:
```typescript
// deno-postgres inernal code
let returnedResult = []
const queryResult = query(...)
const rows = queryResult.rows
const columns = queryResult.rowDescription.columns
const columnNames: string[] = columns.map((column) => {
  return column.name;
});
rows.forEach((row, rowIndex) => {
  let rowData: any = {};
  row.forEach((rVal, rIndex) => {
    const columnName: string = columnNames[rIndex];
    rowData[columnName] = row[rIndex];
  });
  returnedResult.push(rowData);
});
returnedResult = userDefinedQueryData.limit === 1 ? returnedResult[0] :  returnedResult
return {
  query: ...
  ...
  rows: returnedResult
}

// user code
const result = client.query(...)
const rows = result.rows // [{ name: "Edward"}, {name: "Hayd"} }]
```
(Could be improved but you get the gist)

I've actually implemented something similar in a Deno project that uses deno-postgres but that was obviously manual work, and each db query calls that method to get the data in key value pairs

**Comment by dylanpyle** [comment]
FYI: Looks like you can call `result.rowsOfObjects()` to get data out in this format — I agree that this should be the default though! It's much nicer.

**Comment by Soremwar** [comment]
FYI I will be adding a method to query results directly as objects alongside the original function in the upcoming days

**Comment by Soremwar** [comment]
Support for the `queryObject` method was just added in ec3d360
