### ISSUE TITLE
Add support for connecting to linux socket

### ISSUE THREAD

**Issue by ruphin** [denodrivers/postgres#149]
Many cloud services expose hosted database services through linux socket files. Please add a configuration option to connect to a linux socket.

**Comment by cryptogohan** [comment]
Hé, just ran into needing this. Anything I can do to help push it forward? (:

**Comment by Soremwar** [comment]
@cryptogohan I love your enthusiasm man

There is an open PR of like a year ago, where it uses https://doc.deno.land/builtin/unstable#Deno.connect using the socket and unix connection type to achieve the connection, so it should be relatively easy to do, if the original PR was indeed going in the right direction

I don't know anything about sockets, so I was delaying it until I had learned how they work and done something more low level with them, but man if you can give a shot I'll greatly appreciate it

**Comment by cryptogohan** [comment]
@Soremwar hehe, great! I'll try and take a look soon.

Thanks for adding you actually appreciate the enthusiasm haha, I was starting to worry if I was bothering you too much with all this issues activity 😅 .

**Comment by Soremwar** [comment]
@cryptogohan No man, you actually drew my attention to this project yet again. I've been kinda neglecting it for the last couple of weeks but your comments have made me realize how important this is and to stablish a more clear roadmap about what to do to make it better

**Comment by Soremwar** [comment]
Stabilization pending on https://github.com/denoland/deno/issues/13360
