### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by bartlomieju** [denodrivers/postgres#15]

**Comment by bartlomieju** [comment]
This has to wait, because Deno has no TLS support right now.

**Comment by bartlomieju** [comment]
Ref denoland/deno#1568

**Comment by nonnontrivial** [comment]
@bartlomieju now that the relevant Deno issue has closed, is there another blocker for this feature?

**Comment by bartlomieju** [comment]
@nonnontrivial no, not really. As described in #82 I'm spending most of my time on Deno, so if you feel like implementing it - go ahead! Otherwise, I'll tend to it after Deno 1.0 is released

**Comment by nonnontrivial** [comment]
@bartlomieju should the API follow https://node-postgres.com/features/ssl ?

**Comment by bartlomieju** [comment]
@nonnontrivial Deno `connectTLS` API has completely different signature: https://deno.land/typedoc/interfaces/deno.connecttlsoptions.html
The `certFile` argument takes a path to `pem` file which then is used to load all certificates contained in that file. More info: https://docs.rs/rustls/0.16.0/rustls/struct.RootCertStore.html#method.add_pem_file
Final API shape is not that important for now, we can surely work it out during PR review

**Comment by nonnontrivial** [comment]
@bartlomieju okay, excellent. Thank you for the links. I anticipate having time this weekend to get a draft PR up.

**Comment by Soremwar** [comment]
Closed by #249
