### ISSUE TITLE
Insert should return lastidinserted.

### ISSUE THREAD

**Issue by tksilicon** [denodrivers/postgres#154]
Insert should return affectedrows and last id inserted. I am making use of this library in [Dso](https://deno.land/x/dso). Found they were was missing.

**Comment by ebebbington** [comment]
I believe the returned result should give the affected rows (as of latest release):
```typescript
import { QueryResult } from "https://deno.land/x/postgres@v0.4.2/query.ts";
const result: QueryResult = await client.query(...)
if (result.rowCount > 0) {
  console.log('row added')
} else {
  console.log('row was not added')
}
```

**Comment by ebebbington** [comment]
If it was to return the id, do you have an idea of how it would be handled? Obviously it's up to @hayd but i'd assume deno-postgres would want to keep the `QueryResult`, so maybe a new property would be added:
```typescript
const result = ...
if (result.id) {
  // do something with the id of the **affected** row (eg could be included for anything that affected a single row) 
}
```
But even then, not sure how it would get the id internally, without querying the db again, and even so how it would know what to query

**Comment by tksilicon** [comment]
That's correct but lastinsertedid isn't returned. Let me edit my initial comment.

**Comment by andre1sk** [comment]
you can just add RETURING ? and return whatever fields you need ?

**Comment by tksilicon** [comment]
That's interesting, this should work for single inserts I guess. And solve the issue.

**Comment by hayd** [comment]
You kinda want to do `RETURNING MAX(id), count(1)` (so as to avoid sending all the data back, or doing two queries) but that isn't valid...

 > aggregate functions are not allowed in RETURNING

**Comment by ebebbington** [comment]
Couldn't you add `RETURNING id` to the end of the query? Though this would be directly modifying the users query? Idk how things like Laravel implement it? Then i guess there's the question of where/how this data gets returned back to the user (within QueryResult i assume?)

**Comment by tksilicon** [comment]
> Couldn't you add `RETURNING id` to the end of the query? Though this would be directly modifying the users query? Idk how things like Laravel implement it? Then i guess there's the question of where/how this data gets returned back to the user (within QueryResult i assume?)

Could you have two inserts, one for those not interested in returning the id and another for returning the id. So folks like me implementing your library in an ORM where we have other database driver libraries like deno mysql have implemented such.

**Comment by Soremwar** [comment]
I'm not up for mutating user queries. Postgres doesn't have a native mechanism to do this but it still can be implemented in user land with a simple statement

Maybe some other driver might be interested in this. perhaps one more ORM oriented, this one is meant to be more bare bones so it can be easily extendable, making this out of scope for the project
