### ISSUE TITLE
Lack of SSL: Unknown auth message code 1397113172

### ISSUE THREAD

**Issue by Soremwar** [denodrivers/postgres#160]
When using a username that contains @ in it, the login with fail with the following message `Unknown auth message code 1397113172`.

Same happens when a working connection string is provided to the client.

**Comment by Soremwar** [comment]
@hayd After reading some more about the problem, the issue seems to be specific to Azure, which requires to specify a hostname for the user in question.

**Comment by Soremwar** [comment]
@hayd BTW, the problem got solved by forcing Azure to connect through TLS, so it looks like the problem is actually the lack of SSL support in the library.

Leaving this open as a reminder for implementing that funcionality.

**Comment by hoangtranson** [comment]
I get this issue when I try to connect to heroku postgresql also.

My `db.ts` file

```
import { Pool } from "https://deno.land/x/postgres/mod.ts";
import { config } from "./config.ts";

const port = config.DB_PORT ? parseInt(config.DB_PORT || "") : undefined;

const POOL_CONNECTIONS = 20;
const dbPool = new Pool({
  port,
  hostname: config.DB_HOST,
  user: config.DB_USER,
  database: config.DB_NAME,
  password: config.DB_PASS
}, POOL_CONNECTIONS);

export { dbPool };
```

Then I get this issue on terminal.

```
error: Uncaught (in promise) Error: Unknown auth message code 1397113172
        throw new Error(`Unknown auth message code ${code}`);
              ^
    at Connection.handleAuth (connection.ts:197:15)
    at Connection.startup (connection.ts:155:16)
    at async Pool._createConnection (pool.ts:32:5)
    at async pool.ts:61:7
    at async Promise.all (index 0)
    at async Pool._startup (pool.ts:63:25)
```

Note:

1. My code working fine with localhost database (I am using linux pop os)
2. This issue happened on one of my teammate. He using MAC Pro and I have compared the .conf file and see that there is little different between MAC and Linux.

Anyone have any clue?

**Comment by Soremwar** [comment]
@hoangtranson SSL support has been added 0.8.0

If you still encounter this problem, feel free to open a new issue
