### ISSUE TITLE
PostgreSQL's bigint type should be treated as BigInt rather than String

### ISSUE THREAD

**Issue by kaleidawave** [denodrivers/postgres#177]
Have seen #91 and understand not to decode to `Number` for Postgres BigInt types. BUT [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) would be more intuitive than String and get around the bounds issue.

Would be a simple change and I could write PR?

**Comment by Soremwar** [comment]
Solved in #204
