### ISSUE TITLE
Support for unimplemented mappings

### ISSUE THREAD

**Issue by uki00a** [denodrivers/postgres#184]
## Summary

When using types that are not implemented in [decode.ts](https://github.com/deno-postgres/deno-postgres/blob/master/decode.ts), the following error occurs:

```shell
Error: Don't know how to parse column type: <oid>
```

The following is a list of oids for which mapping is not yet supported:

- [ ] 22
- [x] 27 (#228)
- [ ] 28
- [ ] 29
- [ ] 30
- [ ] 32
- [ ] 71
- [ ] 75
- [ ] 81
- [ ] 83
- [x] 199 (#179)
- [ ] 210
- [ ] 325
- [x] 600 (#185)
- [x] 601 (#233)
- [x] 602 (#235)
- [x] 603 (#234)
- [x] 604 (#236)
- [x] 628 (#232)
- [x] 629 (#232)
- [ ] 702
- [ ] 703
- [ ] 704
- [ ] 705
- [x] 718 (#237)
- [x] 719 (#237)
- [ ] 790
- [ ] 791
- [x] 1000 (#189)
- [x] 1001 (#189)
- [ ] 1006
- [ ] 1008
- [x] 1010 (#228)
- [ ] 1011
- [ ] 1012
- [ ] 1013
- [ ] 1016
- [x] 1017 (#185)
- [x] 1018 (#233)
- [x] 1019 (#235)
- [x] 1020 (#234)
- [x] 1021 (#227)
- [x] 1022 (#227)
- [ ] 1023
- [ ] 1024
- [ ] 1025
- [x] 1027 (#236)
- [ ] 1028
- [ ] 1033
- [ ] 1034
- [x] 1115 (#229)
- [x] 1182 (#231)
- [x] 1183
- [x] 1185 (#229)
- [ ] 1186
- [ ] 1187
- [x] 1231
- [ ] 1248
- [ ] 1263
- [x] 1270
- [ ] 1560
- [ ] 1561
- [ ] 1562
- [ ] 1563
- [ ] 1790
- [ ] 2201
- [ ] 2249
- [ ] 2275
- [ ] 2276
- [ ] 2277
- [ ] 2279
- [ ] 2280
- [ ] 2281
- [ ] 2282
- [ ] 2283
- [ ] 2287
- [ ] 2776
- [ ] 2842
- [ ] 2843
- [ ] 2949
- [ ] 2970
- [ ] 3115
- [ ] 3220
- [ ] 3221
- [ ] 3310
- [ ] 3500
- [ ] 3614
- [ ] 3615
- [ ] 3642
- [ ] 3643
- [ ] 3644
- [ ] 3645
- [x] 3807 (#179)
- [ ] 3831
- [ ] 3838
- [ ] 3904
- [ ] 3905
- [ ] 3906
- [ ] 3907
- [ ] 3908
- [ ] 3909
- [ ] 3910
- [ ] 3911
- [ ] 3912
- [ ] 3913
- [ ] 3926
- [ ] 3927
- [ ] 4066

Please see [117#issuecomment-683205862](https://github.com/deno-postgres/deno-postgres/issues/117#issuecomment-683205862) for details.

## Related issues

- #117
- #128
- #178

**Comment by Soremwar** [comment]
After adding support for some of these types in the last days, I have decided that I will ship an `starter pack` of types that will have official support from the library. I have nearly completed that list, only lacking support for geometry types and date arrays.

After that list is completed, the default behavior of the app when it can't parse a result will be to return it as a string to the user, leaving up to them any possible transformation they want to make. From there, I will review possible data types to support officially on a case by case basis.

**Comment by Soremwar** [comment]
4376f4e just enabled string result as a default

**Comment by Soremwar** [comment]
Before 1.0, all types that must be parsed as something other than a string must be scratched from this list

**Comment by bombillazo** [comment]
We need to keep tracking these.

**Comment by bombillazo** [comment]
CLosing to track in a new issue
