### ISSUE TITLE
Just importing the module to a 1.6.0 deno project gives error

### ISSUE THREAD

**Issue by spoyri** [denodrivers/postgres#186]
![image](https://user-images.githubusercontent.com/34547503/101547239-a2030180-39b2-11eb-9a1c-3201063cfe5d.png)

**Comment by StefanHoutzager** [comment]
Got the same

**Comment by StefanHoutzager** [comment]
Looks like this is the fix     /* Old code in utils.ts
    export function delay<T>(ms: number, value?: T): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    setTimeout(() => {
      resolve(value);
    }, ms);
  });
} */
// fixed:
export function delay<T>(ms: number, value: T | PromiseLike<T>): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    setTimeout(() => {
      resolve(value);
    }, ms);
  });
}

**Comment by Soremwar** [comment]
Closed by #187
