### ISSUE TITLE
Export PoolClient from `mod.ts`

### ISSUE THREAD

**Issue by dylanpyle** [denodrivers/postgres#196]
Writing code that needs `PoolClient` types is a bit unwieldy because you have to specify the dependency twice and reach into internal code to get it:

```
// an excerpt from my `deps.ts`
export { Pool } from "https://deno.land/x/postgres@v0.4.6/mod.ts";
export { PoolClient } from "https://deno.land/x/postgres@v0.4.6/client.ts";
```

Consider exporting this in `mod.ts` — which you already do for the regular `Client` — to make this easier.

(I'm working on this and will have a pull request momentarily, just opening this issue first per the contribution guidelines)

**Comment by Soremwar** [comment]
Sorry to check on this just now. What would be the point of exposing PoolClient? It isn't mean to be used as an standalone but rather through the Pool

**Comment by dylanpyle** [comment]
@Soremwar sorry, should have clarified — I'm not interested in using the class itself, just exposing the type definition.

I have code that calls `release()` e.g:


```ts
  const client: PoolClient = await pool.connect();
  await client.query('select * from users;');
  await client.release();
```

— you could omit the type annotation there but it's nice to have, and the specific case I ran into was a bit more complicated than that (declared the variable in a different place than I made the connection, so I actually did need a type to avoid an implicit `any`).

There are probably more complex ways I could pull it out via `typeof` or something, but didn't see much harm in exposing it. If you're concerned about people (mis)using the class itself I believe I could also make it just an `export type { PoolClient }` instead of the whole class.

... or I could just keep pulling out manually if you'd rather keep this as an implementation detail! No worries if so, just seemed nice to have.

**Comment by dylanpyle** [comment]
closing this since #197 was declined - no worries!
