### ISSUE TITLE
Property 'url' does not exist on type 'NetPermissionDescriptor' 

### ISSUE THREAD

**Issue by manojap** [denodrivers/postgres#200]
Property 'url' does not exist on type 'NetPermissionDescriptor'.
              return pd.url

failed to connect

**Comment by Soremwar** [comment]
@manojap Can you share some code?

**Comment by manojap** [comment]
I got it , place  imports in a separate file, which cause the error

The problem also exist with denon too

**Comment by Soremwar** [comment]
So, is this solved?

**Comment by manojap** [comment]
yes,
