### ISSUE TITLE
Make debugging easier by including query in postgres error

### ISSUE THREAD

**Issue by Soremwar** [denodrivers/postgres#216]
More often than not I have to log my executed queries to find syntax problems but have to do it outside of the query in order to get the executed query

**Comment by lionel-rowe** [comment]
This would be huge! Native SQL errors are pretty terrible ("syntax error near user_id") but even worse if you can't see what the raw query was.

**Comment by bombillazo** [comment]
While not directly the same solution, now you can make queries loggable with the new debug option
