### ISSUE TITLE
Named query parameters

### ISSUE THREAD

**Issue by Soremwar** [denodrivers/postgres#223]
I want to do this
```ts
await client.queryArray(
  "SELECT ID, NAME FROM PEOPLE WHERE AGE > $MIN_AGE AND AGE < $MAX_AGE", {
  min_age: 10,
  max_age: 20,
});
```

The same way the following can be done
```ts
await client.queryArray(
  "SELECT ID, NAME FROM PEOPLE WHERE AGE > $1 AND AGE < $2",
  10,
  20,
);
```

**Comment by pantapita** [comment]
I have already worked on this because I had problems figuring out which out many parameters is not placed correctly. You can assign this one to me.

**Comment by tv42** [comment]
This seems to exist already, with different syntax:

```
await client.queryArray`
  SELECT ID, NAME FROM PEOPLE WHERE AGE > ${min_age} AND AGE < ${max_age}
`;
```

The docs were confusing to me for a while...

**Comment by robertvanhoesel** [comment]
@tv42 it's not strictly the same, as you can't pass any options when querying with a template string function but it's definitely a nice and compact way to write queries without mapping any of your existing variables.

> Obviously, you can't pass any parameters provided by the QueryOptions interface such as explicitly named fields, so this API is best used when you have a straight forward statement that only requires arguments to work as intended. — [Docs](https://deno-postgres.com/#/?id=template-strings)

Being able to name the params (rather than $1, $2, $..., which  also happens with the template function, it does not read the variable name but rather the expression output) could help with identifying variables in i.e. logging.

**Comment by Soremwar** [comment]
Yeah, mi idea for this is providing something like
```ts
await queryArray("SELECT $parameter_1, $parameter_2", {parameter_1: 1, parameter_2: "something"})
```
for easier understanding of queries and parameter placing

@tv42 What you are using are template queries, I have updated the docs to make it a hella more clear what they do cause the syntax looks very similar but does way different things

**Comment by pantapita** [comment]
I am using it already in my local fork and it is huge improvement in readability of queries with large number of parameters. But I'm stuck (lack of time and ideas) how to make the query function to automatically detect that this specific query is using named parameters...

(I'm now using a workaround - with additional switch "named_parameters", but I'm not happy with this kind of solution)

I will create a fresh fork with this implementation to share with yall

**Comment by tv42** [comment]
> Being able to name the params (rather than $1, $2, $..., which also happens with the template function, it does not read the variable name but rather the expression output) could help with identifying variables in i.e. logging.

One interesting gimmick would be for template queries to use the part `${here}` as the variable name for the SQL query.

`${foo+42}` style things could be translated to `foo_42`, and suffixes `_2`, `_3` could be added until the variable name was unique.

**Comment by robertvanhoesel** [comment]
@tv42 it's a nice idea but you can't get to the "holes" in a template literal. These things are called tagged templates and only give you the strings surrounding the variables, and the expression output, not the expression itself.

@pantapita what you mean detecting? The `... $1...` vs `.. $myvar` is a distinct syntax you can check for presence using i.e. regex. Better yet, when `queryArray(...)` is being called with two arguments, where the first is text and the second an object (instead of an array) you could imply it's an variable replacement object.

**Comment by pantapita** [comment]
> @tv42 it's a nice idea but you can't get to the "holes" in a template literal. These things are called tagged templates and only give you the strings surrounding the variables, and the expression output, not the expression itself.
> 
> @pantapita what you mean detecting? The `... $1...` vs `.. $myvar` is a distinct syntax you can check for presence using i.e. regex. Better yet, when `queryArray(...)` is being called with two arguments, where the first is text and the second an object (instead of an array) you could imply it's an variable replacement object.

actually you are right, it is sufficient to check for the first argument, if it's not numeric, conclusion is that query is named, thanks.
(was boiling some tedious checks which were way too complex for this simple purpose)

**Comment by pantapita** [comment]
[https://github.com/denodrivers/postgres/pull/358](url)

**Comment by divmgl** [comment]
https://github.com/denodrivers/postgres/issues/223#issuecomment-985786324

This is unsafe and prone to SQL injection.

**Comment by Soremwar** [comment]
@divmgl I don't follow, how is it unsafe?

**Comment by divmgl** [comment]
> @divmgl I don't follow, how is it unsafe?

Forgive me, I was wrong. The `${}` syntax made it look like a regular interpolated string but I realize now it's a templated function.

**Comment by Soremwar** [comment]
@divmgl Oh, haha you scared me for a moment
