### ISSUE TITLE
Object query - easy management with interface like types.

### ISSUE THREAD

**Issue by JADSN** [denodrivers/postgres#241]
#### I need to declare the type `QueryObjectResult<Record<string, unknown>>` for `client.queryObject(query)` and ` Record<string, unknown>[]` for `rows`

![image](https://user-images.githubusercontent.com/7506354/106750596-cbcd5300-6606-11eb-9e63-4dcb000a131d.png)

##### Thanks.

**Comment by Soremwar** [comment]
Hey there @JADSN 

Your code can translate roughly into the following:
```ts
// I recommend not to use "select *" for object queries
const query = "SELECT ID, DESCRIPTION FROM TAGS";
const dbResult = await client.queryObject<Tag>(query);
client.release();
return dbResult.rows;
```

Pretty sweet, uh?

In the future though, please refrain from opening issues unless it's to report bugs or unexpected behaviors. Instead, hit me up on discord https://discord.com/invite/HEdTCvZUSf
