### ISSUE TITLE
Test authentication methods using both TLS and uncrypted connections

### ISSUE THREAD

**Issue by Soremwar** [denodrivers/postgres#250]
Add SSL tests that run on every authentication method (need to figure out how to generate SSL certificates for Docker images)

**Comment by nalanj** [comment]
Can you say a little more about "every authentication method"? And are you open to us requiring docker to run the tests to make it dead simple?

**Comment by Soremwar** [comment]
@nalanj The idea is quite simple, use a docker image and a custom `pg_hba.conf` to test MD5, trust and clear authentication methods (both TLS and non TLS encrypted). I'm working on this

**Comment by nalanj** [comment]
Cool - wasn't sure if I could lend a hand or not. I'll keep pushing on SSL related stuff.

**Comment by lucacasonato** [comment]
Partially done now. At least server TLS is now tested. Still missing client TLS.

**Comment by Soremwar** [comment]
I just opened an issue for that #327. Still don't know how to tackle that though
