### ISSUE TITLE
Template strings and INSERT statements

### ISSUE THREAD

**Issue by realStandal** [denodrivers/postgres#255]
* Deno Version: `1.7.4`
* Deno-Postgres Version: `0.8.0`
* Database: `CockroachDB`

I'm trying to run an `INSERT` statement using a `Pooled` connection and template strings. The following is the query being ran:

```TypeScript
const result = await client.queryObject(
  `INSERT INTO acme.warehouses (warehouse_id, warehouse_name) VALUES (default, ${'charleston'})`,
  name,
);
```

Where `${'charleston'}` comes from a variable and throws the following:

```bash
error: Uncaught (in promise) PostgresError: column "charleston" does not exist
    return new PostgresError(parseWarning(msg));
         ^
    at parseError (warning.ts:34:10)
    at Connection.processError (connection.ts:613:19)
    at Connection._simpleQuery (connection.ts:476:20)
    at async Connection.query (connection.ts:712:16)
    at async mod.ts:99:20
```

The following two queries **do**, however, work:

```TypeScript
const result = await client.queryObject(
  "INSERT INTO acme.warehouses (warehouse_id, warehouse_name) VALUES (default, 'charleston')"
);

const result = await client.queryObject(
  "INSERT INTO acme.warehouses (warehouse_id, warehouse_name) VALUES (default, $1)",
  "charleston",
);
```

I've created and referenced the connection [as recommended by the docs](https://deno-postgres.com/#/?id=pools).

**Comment by Soremwar** [comment]
Hi there @realStandal 

I understand your confusion, however this is pretty simple to explain. You are mixing up two different concepts when executing a query: Template strings and function parameters

In the cases you described above, the following is executed by the driver:

```ts
const result = await client.queryObject(
  "INSERT INTO acme.warehouses (warehouse_id, warehouse_name) VALUES (default, 'charleston')"
);
// Plain statement executed as is

const result = await client.queryObject(
  "INSERT INTO acme.warehouses (warehouse_id, warehouse_name) VALUES (default, $1)",
  "charleston", // Query parameters
);
// Prepared statement, on execution time your database will understand that the value $1 maps to, is "charleston" in this case
```

```ts
const result = await client.queryObject(
  `INSERT INTO acme.warehouses (warehouse_id, warehouse_name) VALUES (default, ${'charleston'})`,
  name,
);
```
This is actually a plain statement, cause you are not using query parameters or template strings, causing your query to be passed to PostgreSQL as the following

```sql
INSERT INTO acme.warehouses (warehouse_id, warehouse_name) VALUES (default, charleston)
```

And since charleston is not surrounded by single quotes and doesn't map to any query parameter, it's though to be a database column rather than a literal value

In order to execute a query the way you intend it, means rewriting it into the following:

```ts
// Using template strings
const result = await client.queryObject`INSERT INTO acme.warehouses (warehouse_id, warehouse_name) VALUES (default, ${'charleston'})`;

// Using plain text
const result = await client.queryObject(
  // Notice the extra quotes surrounding "charleston"
  `INSERT INTO acme.warehouses (warehouse_id, warehouse_name) VALUES (default, '${'charleston'}')`,
);
```

**Comment by realStandal** [comment]
Wow, that is painfully simple. Thank you for taking the time to explain it.

The extra `name,` in the first snippet was a typo on my part, my code didn't actually look like that sorry. Other than that, I think I do understand it and didn't realize I'd need to throw the quotes around it myself; but again that's really obvious now that you point it out.

**Comment by Soremwar** [comment]
You only need to add the quotes around it if you aren't using template strings or query parameters, since in those cases the driver will understand that you mean to pass those items as parameters rather than executing a plain query

Happy to help you @realStandal

**Comment by realStandal** [comment]
Now I see where my _real_ mistake was at, I should invest in reading glasses is my biggest takeaway. Thank you again lol.

**Comment by tv42** [comment]
I just got stumped by this too.

Could I suggest changing the documentation at https://deno-postgres.com/#/?id=prepared-statement-with-template-strings to emphasize that it's a tagged string literal, and not just backquotes.

I think the way to example code is displayed is absolutely hurting, making the tagged string harder to recognize. Could I recommend rewriting

```
  const result = await client.queryObject
    `SELECT ID, NAME FROM PEOPLE WHERE AGE > ${min} AND AGE < ${max}`;
```

as

```
  const result = await client.queryObject`
    SELECT ID, NAME FROM PEOPLE WHERE AGE > ${min} AND AGE < ${max}
  `;
```
