### ISSUE TITLE
Support postgresql:// for protocol

### ISSUE THREAD

**Issue by nalanj** [denodrivers/postgres#258]
I'm not sure if it was an oversight or otherwise, but the library supports connection strings beginning with `postgres://` but not `postgresql://`, despite the fact that `postgresql://` is [the official libpq way of doing things](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING). Not too big of a deal, but it definitely threw me off a bit at first when postgresql wasn't working.

I'm simply asking here first - I'm more than happy to put together a quick PR to handle this.

**Comment by talentlessguy** [comment]
a PR would be very welcome

**Comment by nalanj** [comment]
@Soremwar this seem reasonable to you?

**Comment by Soremwar** [comment]
@nalanj Feel free to open a PR if you want, though I don't think it will be a deal breaker for most

**Comment by nalanj** [comment]
Yep, definitely not a deal breaker. I more just saw it as a rough corner that I could smooth out super easily.

**Comment by nalanj** [comment]
Closed by #260
