### ISSUE TITLE
Shouldn't try/finally be used for releasing pool connection?

### ISSUE THREAD

**Issue by al6x** [denodrivers/postgres#276]
Hi, I noticed that connection pool example is not using `try/finally`, so if error happens the connection may not be released. Shouldn't it be rewritten with `try/finally`, or do I miss something?

```TypeScript
async function runQuery(query: string) {
  const client = await pool.connect();
  try { const result = await client.queryObject(query); }
  finally { client.release(); }
  return result;
}

await runQuery("SELECT ID, NAME FROM users"); // [{id: 1, name: 'Carlos'}, {id: 2, name: 'John'}, ...]
await runQuery("SELECT ID, NAME FROM users WHERE id = '1'"); // [{id: 1, name: 'Carlos'}, {id: 2, name: 'John'}, ...]
```

P.S. Also, a question, would the connection pool auto-reconnect if DB/network goes offline and then comes back?

**Comment by Soremwar** [comment]
This issue went totally over my head

> Shouldn't it be rewritten with try/finally
Yes, I will correct the docs to reflect that, thanks for the heads up!

> would the connection pool auto-reconnect if DB/network goes offline and then comes back
As of now, it won't, and I don't have a clear path to implement that functionality, but I'm aware this is a problem that needs to be addressed

**Comment by al6x** [comment]
> As of now it won't, and I don't have a clear path to implement that functionality, but I'm aware this is a problem that needs to be addressed

I implemented re-connection (and also lazy-connenction) in my wrapper, see the `withConnection` method https://github.com/al6x/deno/blob/main/db/db.ts#L155 . Basically if there's any DB error it kills the current pool with all the connections, and will re-connect on the next request.
