### ISSUE TITLE
Skip the unstable flag

### ISSUE THREAD

**Issue by eveningkid** [denodrivers/postgres#277]
Hey,

I just upgraded to 0.11 that needs the unstable flag when running and was wondering what was the latest version not requiring it?

I understand this is necessary for TLS but it is a blocker for me at the moment to add this flag.

Also, is the previous version not requiring the unstable API okay to use? Or is there security concerns to have?

Thank you!

**Comment by Soremwar** [comment]
Hi there @eveningkid . Even though `deno-postgres` will always attempt to stablish a TLS connection, if such a connection attempt fails and you haven't inforced it in your client configuration it will default to a non-encrypted connection. There was a bug on 0.11.0 that prevented this behavior though, but it was quickly fixed for 0.11.1 thanks to your report

Yo should be able to connect without TLS to your database once more without the need for `--unstable` on your app

> is the previous version not requiring the unstable API okay to use?
It's always recommended that you use TLS to connect to your database, it is a security concern that you should try to sort out if you communicate with your database through a public IP

**Comment by eveningkid** [comment]
Thank you so much for all the details, Steven.

It really fills my heart with joy to see someone spending so much of his time on making a repo great for everyone.

Keep it up, have a great day
