### ISSUE TITLE
Custom CA cert

### ISSUE THREAD

**Issue by jfedyczak** [denodrivers/postgres#284]
I'm trying to connect to DigitalOcean-hosted postgres from linux box (also DO-hosted). While connecting from CLI using psql works fine using TLS, deno can't connect, reporting:

```
Sending fatal alert BadCertificate
error: Uncaught (in promise) InvalidData: invalid certificate: UnknownIssuer
          this.#conn = await Deno.startTls(this.#conn, { hostname });
                       ^
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpAsync (deno:core/core.js:230:12)
    at async Object.startTls (deno:runtime/js/40_tls.js:69:17)
    at async Connection.startup (https://deno.land/x/postgres@v0.11.2/connection/connection.ts:266:24)
```

I tried supplying DO cert file using `--cert <file.pem>` param, I tried installing the cert system-wide. I tried extracting the cert from Postgres server using openssl s_connect. No success. Can anyone help?

Using:
```
$ deno --version
deno 1.9.2 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.5
typescript 4.2.2
```

**Comment by Soremwar** [comment]
Hi there @jfedyczak .

Sadly I have tried this myself many times without success, it seems Deno's defaults are way to strict to bypass this behavior. Only advise I can give you right now is to connect without TLS for the time being, unless you are willing to get a trusted TLS certificate

**Comment by jfedyczak** [comment]
@Soremwar Thanks for prompt reply. Unfortunately not an option in Digital Ocean.

**Comment by jfedyczak** [comment]
Maybe this will help someone. I put pgbouncer on the same machine between the app and the database, so connections from Deno to pgbouncer are unencrypted, but pgbouncer uses TLS to connect to real database server.

**Comment by organic-software** [comment]
I'm encountering the same error with a postgres server on the same box. 

Are there any other workarounds or specific changes needed from Deno side? If TLS doesn't work, it seems like a hard blocker towards using this for anything.

**Comment by Soremwar** [comment]
TLS works perfectly @organic-software , unsafe TLS is the thing that you are currently locked up from using. By that point you are better off not using TLS at all

**Comment by jfedyczak** [comment]
Actually Deno is more picky than `psql` in that matter. In Deno I have this problem with certificate that is perfectly fine for `psql` CLI tool.

**Comment by cryptogohan** [comment]
@Soremwar I came here from asking the Deno people about [adding custom CA certs at runtime](https://github.com/denoland/deno/issues/10735) and it appears there is an option in [Deno.startTls](), it's already being used [here](https://github.com/denodrivers/postgres/blob/master/connection/connection.ts#L266), forking and seeing if passing a cert would resolve my issues! I can spare a bit of time for this but if I run into issues, I'll report back here and leave it at that.

Perhaps also useful to add my use-case. I'm deploying on Digital Ocean Apps platform, it has managed databases, those database require SSL, but only make the CA_CERT available at runtime in an environment variable.

**Comment by cryptogohan** [comment]
Mmm, for others reading along, Digital Ocean just started working fine when I changed from using a connection string (that has a required SSL bit) to using the individual environment parameters. No clue why.

My issue is solved so I'll hold off on forking and adding a connection option that lets you pass a CA cert to `Deno.startTls` but that appears to be a solution. I'd still love to have the option, because I'd rather have SSL on the DB connection than not of course!

**Comment by cryptogohan** [comment]
Alright, ended up going way down the rabbit hole, added a cert option. Sadly something still goes wrong. Spent hours trying to make progress but no. Seems you'd need an intimate understanding of the connection negotiation between pg and Deno. Hopefully, some form of treat-unsafe-domain-as-safe flag lands soon, or someone writes or updates a driver to work with a passed cert file.
