### ISSUE TITLE
Introduce a transpile safe check

### ISSUE THREAD

**Issue by cryptogohan** [denodrivers/postgres#305]
v. weird error. When using `Deno run` with `--no-check` it suddenly _doesn't_ run anymore.

```
error: Uncaught SyntaxError: Unexpected token ';'
    _query: Query<ResultType.ARRAY>,
                                   ^
    at <anonymous> (https://raw.githubusercontent.com/denodrivers/postgres/master/client.ts:68:36)
```

All I could find was this issue:
https://github.com/MikaelPorttila/rss/issues/23
https://github.com/denoland/deno/issues/10684

Any idea what's going wrong?

**Comment by Soremwar** [comment]
As suggested by Kitsonk, this is likely cause by bad imports/exports in the library internals. I will probably introduce a CI step to typecheck and test (with no type check) separately

**Comment by bartlomieju** [comment]
@Soremwar if this is still happening in `--no-check` mode then it's a big red flag that something is broken in Deno's transpilation pipeline. I think we could easily verify this in CI, but running a parallel step with `--no-check` argument, WDYT?

**Comment by Soremwar** [comment]
@bartlomieju I wonder if we can match these results by running `deno test --no-check`

I'll introduce a no check step right away, should be a good way to keep track of SWC problems

**Comment by bartlomieju** [comment]
>  I wonder if we can match these results by running deno test --no-check

I'm not sure what you mean here @Soremwar?

**Comment by Soremwar** [comment]
The code that is breaking is running through `deno run --no-check`, so I'm not sure `deno test --no-check` will yield the same results

**Comment by Soremwar** [comment]
### End result:

No-check failure is not gonna be terminal, however it will produce the following output that should make it easy to file an issue in Deno

![image](https://user-images.githubusercontent.com/42647963/149027795-c2ae1144-e57c-4ad5-b3de-535a14c7c9e3.png)

Right now, `deno-postgres` should be no-check safe when running through `deno test --no-check` under Deno 1.16.0
