### ISSUE TITLE
Invalid EXPLAIN results

### ISSUE THREAD

**Issue by coreybutler** [denodrivers/postgres#312]
It appears the `EXPLAIN` command isn't parsing/processing results correctly.

Consider the following statement executed in DBeaver:

![image](https://user-images.githubusercontent.com/770982/128963189-4e53c543-4fc8-4307-871b-da835bf3f793.png)

Now consider the same thing in Deno-Postgres:

```javascript
await conn.connect()

const r = await conn.query(`
  EXPLAIN SELECT *
  FROM account.acct a
      JOIN account.acct_user au on a.id = au.acct_id;`
)

console.log(JSON.stringify(r, null, 2))
```

![image](https://user-images.githubusercontent.com/770982/128963419-91e4d82a-0a7c-47fe-a2b6-d5f53d069c40.png)

Only the second result exists in the Deno-postgres output (I expected the results to match the output of DBeaver).

**Comment by Soremwar** [comment]
Hello there @coreybutler. I'm testing with the latest driver version `https://raw.githubusercontent.com/denodrivers/postgres/72f523cb9d8f863204a3fa02f52d534e7ce30ccf/mod.ts` and I can't seem to be able to replicate this problem

I believe this had to do with the way I was evaluating arrays when coming as a response from Postgres, which was recently refactored

Try and see if you can replicate locally, I'll assume this issue is closed in the meanwhile

**Comment by coreybutler** [comment]
In a simple demo, I also cannot recreate the problem. However; I have a class with a function that executes a serializable transaction. When executing the exact same code from that class, there are missing results. I'll keep hunting today and post my findings when I narrow down the problem.

**Comment by coreybutler** [comment]
I found the issue, and it isn't related to this library. In my case, the query results are written to `stdout` as part of an error/informational message in a unit testing suite. The suite produces TAP output. The raw TAP output displays the results correctly:

![image](https://user-images.githubusercontent.com/770982/135129123-38b9811b-6b1c-4ce8-98aa-fc6ce7fda655.png)

However; displaying pretty results with tap-spec yield output like those from my prior messages. Clearly this is the result of using tap-spec, not deno-postgres.

Thanks for your time, and thanks for your work on this library.
