### ISSUE TITLE
Docs and API reference

### ISSUE THREAD

**Issue by bartlomieju** [denodrivers/postgres#32]
Whole documentation is just a README file, better documentation should be provided as documentation page. 

Public API should be annotated with JSDoc, so auto generated API reference can be obtained.

**Comment by bartlomieju** [comment]
Documentation website is going at [deno-postgres.com](http://deno-postgres.com). 

Let's get to work on documentation itself.

**Comment by linuxguy467** [comment]
deno-postgres.com leads me to Server not found error page

**Comment by hayd** [comment]
oh, no! I missed this happening, will fix it up...

**Comment by Soremwar** [comment]
All public interfaces are quite well documented with JSDOC for doc.deno.land and the official documentation website is quite complete regarding the use of the library's current features
