### ISSUE TITLE
query text array return value be added `,`

### ISSUE THREAD

**Issue by iugo** [denodrivers/postgres#325]
If a string contains a semicolon and a comma, there will be a problem.

text array value: `{"a:b/c;d,e","1,b,2"}`

should return `["a:b/c;d,e","1,b,2"]` but `["a:b/c;d,e",",1,b,2"]`

code:

https://www.typescriptlang.org/play?#code/PTAECEEMGcFMBNQHsBmoAWAXTAHaAuEAcwEtN0BXAIwDoBjJAW2CtgDt4AnCuga1k7AcSaJiKdY0ALSROnSAE8AUCFABhJDgWcSRLKAAUdAJQR2oACLc+A0AB4qANy49+nAAJFGkEgBt6TAB8hqwc1m40jLDGNKAAsgCSACqgADIkdOxwNEoqAFR5oAlsDHKwdJi+CqA4snCI8JCYkKCYCjiSoPCwKJAUvpitSKBs-b6gecBKbR2gAIJyigBKkv2YdknBALzziwoboAA+I2NHu-IKK9BrG4GBANzT7bCgSfJs0ChInFGct6A7AyOSC+CiwfCgUQ6NhEUxbYJJR5KFAUEqYEhINhdHp9AYANRBYKBhPBkMw0NhEKhJBhoAA3kpQKAJJgKJwscDQbBHgBfXIotEYrG1ThwBYXAzQJBszJU8k0ynnZarAZ2akwh7I1EVIU1OqwcWKW4GRmQ6WcWVkikAGlN5MgHy+Pwhbwdn2+v1utuMEMNlxV602jwFOsxetFBr2kvNlvVRGtrXe7p+AOxvTWBK5pgZTJZbKxbFgAHclQoAAr6zjRmWwBP2x0emIiuAGYy83J0XwwaClisRv6bemm4TQMi6nYABkeTPY8skvr2Vxug52AG0ALrT5nlb7deByikb1MbrfwEhRD7j0BT3JMhgfck8TDfE1Mpk4ai+DJmmsHhW2t8ak-b962TRgXSTJ1PU2ADQGzPlTRIaAAFFUFbCEqCQJBfFgB0h0AvN2VadAkJoEcxzDQIdnIUipRrGgcJhcgtwQplCwAD0wNR0FkSAKgEVt8Lfe9RFAOgePkfjOFTGjoBoOiLVgVdZLIkQKLYABqDTN1NJkSDQIwJL4zBbC2MzQAAIgAHSsizs10t9CKxHNALfTkwQhFSFMyZSSLk8j0UxLT11g1zQEkOhIA6fdEzBUK3x5LcmT5AjYFZIiXMA9zSXE3ipPimdoEi6KIV6Xw4HixLTVY7dSngQy8pMzg-xhH1QEcJASEQTLiNIiQ6oQMiKGgdAGskpq22q28RmLZC2HJBQDBpTsKG6ZDGBwNpUzKuA2o6rqhKZHDBlnTgFCS0B9MMFT+t3QbGKIchQGCCcjmOZbQTWja2nssLTuqai-JoW7OD3GgACtOrYAwLLsi69IM-6AXMiyADkAFVUlSCzQAAMlx0AAEIPtW2B1s2hRfrC8L5rO1NRl8Xx4dAFLXKugwkcJ8yGd8UwkcB0jQKgjnacp5mVNOkhJCGkaRYWyawpundQYQY8dMA1mapEigogsc8siFaB0Pazruoc9mvJjJSJ3XZGdgs1c7MOt8ixInDDEJlSkNQlBWypsKRMGXLpIFuSOK4oypNbZmEcMYOaGyu3LK2J2qAkSBeGZ1nkqm01gAKXTCj9HtIqxe9mhpS6TMYHs4BFJpVaoao4EYDJsLDSUeHQUAYFATD2MkYxC57jgxKYbxoEL4ekj8sT0HKXgeyu8gBBeJCR8uh8HUyZA0BaFu298MMwxXoYcFAHDHFgXxh9QYiXlkC5YgSNAyFAItV6GPuXi+VF4DreekJYD12fNJIsfhxisGHvvWArcGBHzYAmJAK9ODgLgFXd+EC0y4kGM+HuY9GDeELlMJkRA0oAGVgG8VAYJHq7NgD3AMAAfkJquAAegYdceQrLGGMMAGgJlRAGEtvRa4VAoQGAAIwANolbBi7BHrdykKASRvD-aOTSvmSy9wLIXWztudKWILLWl0bnd8+oDCFlEKrHYO1ogLguEuVUg4eqByASA74MkgZkMwJQjxVYFZvmOnPRqAgEzNjCaAAAjhQZB3IHIqW1rrfWl5MRG0CUyV2fgXgGE9kDb2aFeHOzvJHJqXjSLh24qEgJzN2bB2MgIBOJIk4WTpDjfGRMYlxPUYBFSZ4LyjiChpGOl0DJ9JSYMrEwRVHFNchEkOM0Sx+j7HAKsDlqa9Tkt5WA8lqASJUgFXUyjVEFWpipIWHpTmAQyWcoGktpYfllvMsiFjHzRBuYrIGhywwaR2M875WJlEACYRn6OSuFcqa8DL1Kkk0rkLSeTtIJoTLpJkelvnGQMoUUgpAjPZnk0i-SDaYnRb0oGhYixzQWtHdZbMDJWJMvAUwTlNk0HudAUFtKeQQvQXU0pjTE5mR2AAcgssKvGyKYVNTZUVKKCBSWjMMKi6IrKKVUrOsI7g0QRnKtTCi2JJks48qhXHflnA4VgiTnXahniOn6u6bMpkKk1WixpWFbl190E9TJX1ZW9UpUCpJB8lmDl9EWyBkS1JWIuaTnReQTgSASwUtAMhOQL4LKP0UF0CZuo2DIL7iCbeCA4ahociyiWtMpYcqmghNxgw-n6j9AYAABm0yA+AqDADoPcf+sBjEWWkVQa0QLjGQCoHQHkzaEzEizACYI2VJpKBEthHZR8iAGGFZgYVdZJpAA

The previous character is `,`, if the next character is `"`, the previous `,` should be removed.

**Comment by Soremwar** [comment]
I see your issue is based in 0.12.0 and not in main

Check #316 for more details, and try again while pulling from main. Closing in the meanwhile
