### ISSUE TITLE
[docs] .release() should be await?

### ISSUE THREAD

**Issue by iugo** [denodrivers/postgres#332]
https://github.com/denodrivers/postgres/blame/e483c80e0c55b001f3d1c497b1517b82166a2301/docs/README.md#L339-L350

`client_1.release();` or `await client_2.release();`?

---

https://github.com/denodrivers/postgres/blame/e483c80e0c55b001f3d1c497b1517b82166a2301/docs/README.md#L362-L368

`result` only in `try` block.

**Comment by Soremwar** [comment]
No, actually by the signature you can see that `pool_client.release` is a sync function, so there is no need for awaiting it
