### ISSUE TITLE
set TIME ZONE 'HongKong'; got Error: Unexpected frame: S

### ISSUE THREAD

**Issue by biluohc** [denodrivers/postgres#335]
deno 1.14.2
PostgreSQL 12.3
macos x86-64 11.6

`client.queryArray("set TIME ZONE 'HongKong';")` or `client.queryObject("set TIME ZONE 'HongKong';")`

```sh
error: Uncaught (in promise) Error: Unexpected frame: S
        throw new Error(`Unexpected frame: ${msg.type}`);
              ^
    at Connection.#simpleQuery (https://deno.land/x/postgres@v0.12.0/connection/connection.ts:681:15)
    at async Connection.query (https://deno.land/x/postgres@v0.12.0/connection/connection.ts:920:16)
```

**Comment by Soremwar** [comment]
Thanks for the report @biluohc. Just patched

**Comment by biluohc** [comment]
Thank， can you publish a new version?

**Comment by Soremwar** [comment]
I am amidst a refactor of several internals that I want to land before 1.13. You can use the patched version with this URL `https://raw.githubusercontent.com/denodrivers/postgres/148e75023ad26cd3391f1e284b9b04712c0a38a8/mod.ts` in the meanwhile, works as a tagged version so no surprises
