### ISSUE TITLE
Why is camelcase disabled for "deno lint"?

### ISSUE THREAD

**Issue by bartlomieju** [denodrivers/postgres#341]
As per title, I'm mostly curious as to why this had to happen.

Is something wrong with the rule? Maybe some cases are marked as false positives?

**Comment by Soremwar** [comment]
Nah, it's because I have my own internal naming convention. Snake case for variables, camel case for functions

**Comment by bartlomieju** [comment]
Thanks for explanation. I guess this is not something I could convince you to change :))
