### ISSUE TITLE
Inconsistency between `client.queryArray` and `transaction.queryArray`

### ISSUE THREAD

**Issue by baoshan** [denodrivers/postgres#379]
These two interfaces differ in treating the arguments. To be specific:

[`transaction.ts`](https://github.com/denodrivers/postgres/blob/b68d3ebfd1a5805050f12e74ddaa4df3185bb86f/query/transaction.ts#L400)
```
query = new Query(
        query_template_or_config,
        ResultType.ARRAY,
        args as QueryArguments | undefined,
      );
```

[`client.ts`]()
```
query = new Query(
        query_template_or_config,
        ResultType.OBJECT,
        args[0] as QueryArguments | undefined,
      );
```

I guest the latter is expected. Can the inconsistency be permanently avoided by removing the duplicated logic?

**Comment by Soremwar** [comment]
Thank you for your report, I can confirm I messed up

I will submit a fix soon
