### ISSUE TITLE
Unnecessary warning: there is no transaction in progress

### ISSUE THREAD

**Issue by baoshan** [denodrivers/postgres#392]
When `commit`ting a transaction, certain errors (e.g., serialization errors) may be [cached](https://github.com/denodrivers/postgres/blob/28c421a6d3d68dcacf5b2c05b31dfb18608db9e0/query/transaction.ts#L414) by `postgres` driver. In the catch clause, `postgres` issues another `commit`. Issuing COMMIT when not inside a transaction does no harm, but it will [provoke a warning message](https://www.postgresql.org/docs/current/sql-commit.html).

This troubles me because my test report is filled with random `WARNING: there is no transaction in progress`, which compromises the readability.

I think muting warning messages is suboptimal. I’ll draft an experimental PR. Please let me know if there are better ways to deal with this. Thanks.

**Comment by Soremwar** [comment]
A system I'm yet to implement is the logging system in the driver. There are many more warnings than just this one, ideally they could all be muted together since their purpose is for debugging only

I don't think the solution to this is to add another method on the commit function though, that much I have clear

**Comment by baoshan** [comment]
Use a logging system to mute this specific `no transaction in progress` warning is suboptimal because the (unnecessary) `COMMIT` statement adds an extra server round trip, which is probably 20~400ms (a transactional query usually targets the primary cluster in a cross-geo clusters).

I’m leaving this issue open because I think logging is not its root cause. Feel free to close it.

Thanks.

**Comment by Soremwar** [comment]
You are right, I should hold the state of the transaction to avoid issuing the commit to the database if the transaction has already aborted

However as I said, the solution is not to add another option to the command method

**Comment by baoshan** [comment]
I’ve updated the PR to track if a transaction has been committed.

This doesn’t handle the situation that the `commit` is not submitted via `transaction.commit()`. Please let me know what do you think.

**Comment by Soremwar** [comment]
> This doesn’t handle the situation that the commit is not submitted via `transaction.commit()`

Could you elaborate on this please?

**Comment by baoshan** [comment]
I mean `transaction.queryArray("COMMIT;")`. Forget about it, that’s an abuse obviously.

**Comment by Soremwar** [comment]
Closed in #393
