### ISSUE TITLE
async functions like queryArray throw instead of reject

### ISSUE THREAD

**Issue by KyleJune** [denodrivers/postgres#401]
https://github.com/denodrivers/postgres/blob/33ca49d57eb615d2922e781191815c9a963c5796/client.ts#L301

Functions like queryArray that return a promise should reject instead of throwing errors. This could be accomplished by making the functions that return promises async so that they will always either resolve or reject.

**Comment by Soremwar** [comment]
Oops, little overlook will fix asap

**Comment by KyleJune** [comment]
> Oops, little overlook will fix asap

Thanks. Also completely understandable, there was actually a bug with assertRejects from std/testing that would cause it to pass for both thrown errors and rejections. That was fixed recently, now it will show if it incorrectly throws when it is expected to reject.

**Comment by Soremwar** [comment]
Fixed now
