### ISSUE TITLE
Login failure in Deno 1.26.2

### ISSUE THREAD

**Issue by coreybutler** [denodrivers/postgres#412]
I have successfully connected with a Pool using Deno 1.25.4. Today I upgraded to Deno 1.26.2, which immediately failed with a bad password. Reverting back to 1.25.x and the connection succeeds again. It looks like something in the 1.26.x branch is causing a basic login failure.

```js
const connection = new Pool(connectionstring, 20, true)
```

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/770982/196570149-174dee96-2e30-4896-9af7-85550aec5acd.png">

**Comment by prettykool** [comment]
I got this same bug, too - Had to downgrade to 1.26.1 to get the client working properly again. I'm guessing something charged with an internal API between versions, but I could be wrong...

**Comment by Soremwar** [comment]
Published 0.17.0 to fix this
