### ISSUE TITLE
[question] how to pass an ILIKE %word%

### ISSUE THREAD

**Issue by silvioprog** [denodrivers/postgres#421]
Hi.

Consider the following code:

```typescript
client.queryObject<PaymentType>`
  SELECT
    description
  FROM
    payment_types
  WHERE
    description ILIKE ${q}`;
```

I have been considering to use something like this:

```typescript
client.queryObject<PaymentType>`
  SELECT
    description
  FROM
    payment_types
  WHERE
    description ILIKE '%${q}%'`;
```

however, it raises syntax error, so I'm considering to use this:

```typescript
client.queryObject<PaymentType>`
  SELECT
    description
  FROM
    payment_types
  WHERE
    description ILIKE ${"%" + q + "%"}`;
```

but I'm not sure if it is safe to prevent SQL injection.

So, how do I pass an `ILIKE %word%` in the safest way?

TIA for any help!

**Comment by Soremwar** [comment]
The last one is the right one

**Comment by silvioprog** [comment]
Wow, thanks a lot @Soremwar for the quick answer. After set my message, I just also found ```${`%${q}%`}```.
