### ISSUE TITLE
commit({ chain: true }) will only commit once

### ISSUE THREAD

**Issue by abrgr** [denodrivers/postgres#427]
In `commit` (https://github.com/denodrivers/postgres/blob/main/query/transaction.ts#L283), we only send a commit to postgres once per transaction. However, with chain: true, we want to be able to commit multiple times. Shouldn't this be modified so that, if chain is true, `this.#committed` is set to false so that you can run multiple `commit({ chain: true })` calls in a row and each will actually be sent to postgres?

**Comment by bombillazo** [comment]
This has been completed
