### ISSUE TITLE
Looking for mantainers

### ISSUE THREAD

**Issue by Soremwar** [denodrivers/postgres#434]
Sorry for the lack of interaction with this community in the last few months

I have distanced myself a lot from software development towards a more artsy focus in my life. This has sadly lead to this project becoming unmantained with no prospects of that changing any time soon

Under my watch this library came a long way, as it should be as the main postgres library in the ecosystem (at least for a while). However there are still many open issues and features that need implementation for this library to be feasible for any serious project

I believe there is a solid foundation to work on these issues, so I'm looking for anyone willing to continue the development of `deno-postgres` and take it where it needs to be. Anyone interested just ping me in this issue

**Comment by bartlomieju** [comment]
Hey @Soremwar, thanks for all the work you did on `postgres` driver! I can take over the maintenance.

**Comment by bombillazo** [comment]
Hey @Soremwar , thanks for the excellent work so far; I'd also like to contribute and help as much as possible as a maintainer.

**Comment by Soremwar** [comment]
Long time no see, @bartlomieju

Sure, I have added you as admin of the project. Happy to see someone step up

**Comment by bartlomieju** [comment]
@bombillazo I could definitely use some help if you're interested :)

**Comment by bombillazo** [comment]
Count me in!

**Comment by bombillazo** [comment]
@bartlomieju count me in!
