### ISSUE TITLE
suggestion: complete documentation

### ISSUE THREAD

**Issue by iuioiua** [denodrivers/postgres#448]
I suggest having documentation for every symbol within this project. One can check for remaining symbols missing documentation by running `deno doc --lint mod.ts`.

**Comment by iuioiua** [comment]
Overlaps #221

**Comment by bombillazo** [comment]
I'm new to JSDocs, and it seems like a pretty daunting task; there were 60 errors in that file alone. Any way this can be auto-generated or have a template for them to fill?

**Comment by iuioiua** [comment]
It might seem more tedious than it is. It's more of a matter of explaining what the symbols do. The [JSDoc documentation](https://jsdoc.app/) is a great reference. To see it in practice, look at the source code of [`deno_std`](https://github.com/denoland/deno_std)—especially the `collections` sub-module.

**Comment by iuioiua** [comment]
You can also use the `/doc` command in GitHub Copilot.
