### ISSUE TITLE
Refactor Pool

### ISSUE THREAD

**Issue by bartlomieju** [denodrivers/postgres#49]
To land #45 I had to disable `Pool` tests, rendering it unusable. Refactor has to be done to `Pool`, some initial thoughts:
- rename `PooledClient` to `PoolClient`
- `Pool` can be constructed from DSN
- pool connection can be created lazily
- size is optional default to 10
- add `Pool.transaction` helper that wraps `Pool.query` in transaction

**Comment by runnerSnail** [comment]
Excuse me, can I use ` PooledClient `?

**Comment by bartlomieju** [comment]
@runnerSnail as noted above, if you use `master` then `PooledClient` is broken. Although if you're running latest release then you can use `PooledClient`, but don't use it to create connection, instead do this:
```ts
const pool = new Pool({
    database: "test",
    user: "test",
    ....
}, 10);

// then you can do one-off queries like this
await pool.query("SELECT * FROM my_table;");
// or get client from pool
const client = await pool.connect();
client.query("SELECT * FROM my_table;");
// remember to release the client back to pool
client.release();
```

**Comment by runnerSnail** [comment]
okey,thanks!

**Comment by bartlomieju** [comment]
@mhvsa will you look at it?

**Comment by hayd** [comment]
What about `ClientPool`? I think that reads a little better.
Although in node-postgres it's just called [Pool](https://node-postgres.com/features/pooling).

 I will take a look at this.

**Comment by mattbishop** [comment]
Ideally this lib would look like node-postgres as much as possible to aid transitions.

**Comment by hayd** [comment]
Looking again, and rereading the issue, I don't think the pool tests are disabled.
